version: '3.8'
services:
  # Apache Zookeeper (required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Apache Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # Internal listener (for other services)
      - "9093:9093" # External listener (for local machine access/tools)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Define listeners for internal and external access
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Essential for a single-broker setup (not for production clusters)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine # Lightweight Alpine image
    hostname: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  # Redis Cache/Session Store
  redis:
    image: redis:7-alpine # Lightweight Alpine image
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # Enable persistence
    volumes:
      - redis_data:/data # Persist data
  
  # New PostgreSQL database for the Order Service
  order_db:
    image: 'postgres:14.5-alpine'
    container_name: order_db
    environment:
      POSTGRES_DB: order_db # Database name
      POSTGRES_USER: orderuser # Database user
      POSTGRES_PASSWORD: orderpassword # Database password
    ports:
      - '5432:5432' # Map host port 5433 to container port 5432. This avoids conflict with your existing 'postgres' on 5432.
    volumes:
      - order_db_data:/var/lib/postgresql/data # Persistent data volume for order_db
    networks:
      - app-network
    healthcheck: # Keep the healthcheck, it's good practice
      test: ["CMD-SHELL", "pg_isready -U orderuser -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ../backend/order-service # This tells Docker where to find your Spring Boot project
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # This is KEY: Use the service name 'order_db' here, NOT 'localhost'
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/order_db
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpassword
    depends_on:
      order_db:
        condition: service_started # Ensure order_db is ready before order-service starts
    networks:
      - app-network # Must be on the same network as order_db

  

volumes:
  postgres_data:
  redis_data:
  order_db_data: # <-- ADD THIS NEW VOLUME for order_d

networks:
  app-network:
    driver: bridge # 'bridge' is the default and usually sufficient for local development